version: "3.9"

services:

  storage:
    container_name: myapp-mysql
    image: myapp-db-develop
    environment: 
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    build: ./storage
    volumes: 
      - ./data/db:/var/lib/mysql
    networks: 
      - backend-network
  
  redis:
    image: redis:6.2-alpine
    command: redis-server
    ports:
      - 6379:6379
    networks: 
      - redis-network
  
  redis-queue:
    image: myapp-rq-develop
    environment:
      REDIS_URL: redis://redis:6379
      BACKEND_API: http://backend:5000
    build: ./redis-queue
    depends_on: 
      - redis
    networks: 
      - redis-network
  
  backend:
    image: myapp-api-develop
    environment:
      APP_SETTINGS: config.Config
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      REDIS_URL: redis://redis:6379
      DATABASE_URL: mysql+pymysql://user:userpassword@storage/myapp
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes: 
      - ./backend/app:/usr/myapp/app
    depends_on:
      - storage
      - redis-queue
    ports:
      - 5000:5000
    networks: 
      - backend-network
      - redis-network
      - frontend-network
  
  frontend:
    image: myapp-ui-develop
    environment:
      PROXY_TARGET: http://backend:5000
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes: 
      - ./frontend/src:/usr/myapp/src
    depends_on:
      - backend
    ports:
      - 9000:9000
    networks: 
      - frontend-network

networks: 
  redis-network:
  backend-network:
  frontend-network: