version: "3.9"

services:

  backend:
    image: myapp-backend-test
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    command: sh -c "flake8 . && python -m unittest -v"
  
  frontend:
    image: myapp-frontend-test
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm test