version: "3.9"

services:

  storage:
    image: myapp-db-dev
    environment: 
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    build: ./storage
    volumes: 
      - ./data/db-dev:/var/lib/mysql
    networks: 
      - backend-network
  
  redis:
    image: redis:6.2-alpine
    command: redis-server
    ports:
      - 6379:6379
    networks: 
      - redis-network
  
  redis-queue:
    image: myapp-rq-dev
    environment:
      REDIS_URL: redis://redis:6379
      BACKEND_API: http://backend:5000
    build: ./redis-queue
    depends_on: 
      - redis
    networks: 
      - redis-network
  
  backend:
    image: myapp-backend-dev
    environment:
      APP_SETTINGS: myapp.config.Config
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      REDIS_URL: redis://redis:6379
      DATABASE_URI: mysql+pymysql://user:userpassword@storage/myapp
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes: 
      - ./backend/myapp:/usr/app/myapp
    depends_on:
      - storage
      - redis-queue
    command: >
      sh -c './wait-for-it.sh storage:3306 -t 300 && 
             python -m myapp'
    ports:
      - 5000:5000
    networks: 
      - backend-network
      - redis-network
      - frontend-network
  
  frontend:
    image: myapp-frontend-dev
    environment:
      DEV_HOST: 0.0.0.0
      DEV_PORT: 9000
      PROXY_TARGET: http://backend:5000
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes: 
      - ./frontend/src:/usr/app/src
    depends_on:
      - backend
    ports:
      - 9000:9000
    networks: 
      - frontend-network

networks: 
  redis-network:
  backend-network:
  frontend-network: