version: "3.9"

services:

  storage:
    image: myapp-db-prod
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    build: ./storage
    volumes: 
      - ./data/db:/var/lib/mysql
    networks: 
      - backend-network
  
  redis:
    image: redis:6.2-alpine
    command: redis-server
    ports:
      - 6379:6379
    networks: 
      - redis-network
  
  redis-queue:
    image: myapp-rq-prod
    environment:
      REDIS_URL: redis://redis:6379
      BACKEND_API: http://backend:5000
    build: ./redis-queue
    depends_on: 
      - redis
    networks: 
      - redis-network
  
  backend:
    image: myapp-backend-prod
    environment:
      APP_SETTINGS: myapp.config.ConfigProd
      REDIS_URL: redis://redis:6379
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URI: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@storage/${MYSQL_DATABASE}
    build: ./backend
    depends_on:
      - storage
      - redis-queue
    ports:
      - 5000:5000
    networks: 
      - backend-network
      - redis-network
      - frontend-network
  
  frontend:
    image: myapp-frontend-prod
    environment:
      NGINX_PORT: 8080
      PROXY_TARGET: http://backend:5000
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 80:8080
    networks: 
      - frontend-network

networks: 
  redis-network:
  backend-network:
  frontend-network: