FROM python:3.9-slim

WORKDIR /usr/app

RUN apt-get update

COPY requirements*.txt ./
RUN pip install \
    --disable-pip-version-check \
    -r requirements-dev.txt \
    -r requirements.txt

COPY . .
CMD sh -c "flake8 myapp/ && python -m unittest -v"