FROM python:3.9-slim

WORKDIR /usr/app

RUN apt-get update

COPY requirements*.txt .
RUN pip install \
    --disable-pip-version-check \
    -r requirements-dev.txt \
    -r requirements.txt

COPY . .
CMD python -m myapp
# CMD gunicorn --bind 0.0.0.0:${APP_PORT} --log-level debug --reload myapp.wsgi:app