apiVersion: apps/v1
kind: Deployment
metadata:
  name: rq-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      component: redis-queue
  template:
    metadata:
      labels:
        component: redis-queue
    spec:
      containers:
        - name: redis-queue
          image: researchlabai/myapp-rq
          env:
            - name: REDIS_URL
              value: redis://redis:6379
            - name: BACKEND_API
              value: http://backend:5000
