# name: AWS Deployment

# on: workflow_dispatch

# jobs:
#   deploy-app:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out repo
#         uses: actions/checkout@v2
      
#       - name: Set up Python 3.9
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9

#       - name: Install EB cli
#         run: |
#           python -m pip install --upgrade pip
#           pip install awsebcli
#           eb --version