name: Main build & deploy

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/**'
      - 'frontend/src/**'
      - 'frontend/nginx/**'
      - 'frontend/package*.json'
      - 'frontend/webpack.common.js'
      - 'frontend/webpack.prod.js'
      - 'frontend/.babelrc'
      - 'frontend/.eslintrc'
      - 'frontend/Dockerfile'
      - 'backend/myapp/**'
      - 'backend/Dockerfile'
      - 'backend/requirements.txt'
      - '.github/workflows/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      
      - name: Build tag
        id: build_tag
        run: |
          echo "::set-output name=tag::sha-${GITHUB_SHA:0:6}"
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build DB image
        uses: docker/build-push-action@v2
        with:
          context: ./storage
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/myapp-db:latest,
            ${{ secrets.DOCKERHUB_USERNAME }}/myapp-db:${{ steps.build_tag.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      
      - name: TODO
        run: |
          echo "TODO: deployment"