name: Main CI

on: 
  push:
    branches:
      - main

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Lint and Test code
        run: docker-compose -f docker-compose.test.yml up --build