name: Main build & deploy

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/**'
      - 'frontend/src/**'
      - 'frontend/nginx/**'
      - 'frontend/package*.json'
      - 'frontend/webpack.common.js'
      - 'frontend/webpack.prod.js'
      - 'frontend/.babelrc'
      - 'frontend/.eslintrc'
      - 'frontend/Dockerfile'
      - 'backend/myapp/**'
      - 'backend/Dockerfile'
      - 'backend/requirements.txt'
      - '.github/workflows/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
    
      - name: Set up Docker Buildx
        id: buildx_backend
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2